version: '3'
services:
        web:
                image: cartage
                build: .
                env_file:
                        - .env # This file is optional; defaults will be used if it does not exist
                ports:
                        - "4200:4200"
                volumes:
                        - ./instance:/instance
                restart: unless-stopped
        worker:
                image: sqs_worker
                build: ./sqs_worker
                env_file:
                        - .env
                volumes:
                        - ./:/app
                restart: unless-stopped